### ISSUE TITLE
Aop introduction on generic method regression

### ISSUE THREAD

**Issue by bvella** [micronaut-projects/micronaut-core#1667]
### Task List

- [*] Steps to reproduce provided
- [*] Stacktrace (if present) provided
- [*] Example that reproduces the problem uploaded to Github
- [*] Full description of the issue provided (see below)

### Steps to Reproduce

An interface with a generic method, and interface extending it that fixes the generic and an introduction on the latter interface, like so:

```java
public interface GenericPublisher<E> {
    
    void publish(E event);
    
}

public class SpecificEvent {}

@PublisherProxy
public interface SpecificPublisher extends GenericPublisher<SpecificEvent> {}

@Introduction
@Type(PublisherIntroduction.class)
@Bean
@Singleton
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface PublisherProxy {}

@Singleton
public final class PublisherIntroduction implements MethodInterceptor<GenericPublisher<?>, Object> {

    @Override
    public Object intercept(final MethodInvocationContext<GenericPublisher<?>, Object> context) {
        final Method method = context.getTargetMethod(); // works in 1.1.0, fails in 1.1.1
        return null;
    }

}
```

### Expected Behaviour

The correct method is resolved

### Actual Behaviour

 java.lang.NoSuchMethodError: Required method publish(SpecificEvent) not found for class: issue.GenericPublisher. Most likely cause of this error is that an unsupported or older version of a dependency is present on the classpath. Check your classpath, and ensure the incompatible classes are not present and/or recompile classes as necessary.
        at io.micronaut.core.reflect.ReflectionUtils.newNoSuchMethodError(ReflectionUtils.java:425)
        at io.micronaut.context.AbstractExecutable.getTargetMethod(AbstractExecutable.java:109)
        at io.micronaut.aop.chain.MethodInterceptorChain.getTargetMethod(MethodInterceptorChain.java:65)
        at issue.PublisherIntroduction.intercept(PublisherIntroduction.java:18)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
        at issue.SpecificPublisher$Intercepted.publish(Unknown Source)
        at issue.Issue.publish(Issue.java:15)
        at issue.IssueTest.test(IssueTest.java:15)

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.1
- **JDK Version:** 1.8

### Example Application

https://github.com/bvella/micronaut-generics-introduction-issue

the unit test fails in 1.1.1 and works in 1.1.0

**Comment by graemerocher** [comment]
Whilst I agree this is a regression, and should be fixed, why do you need `getTargetMethod()`? This will result in a reflective call and is generally to be avoided

**Comment by bvella** [comment]
I have a library that gives me a java.lanf.reflect.InvocationHandler (for creating a standard java.land.reflect.Proxy) and I used this method to route the calls to the same invocation handler, I have worked around this by changing the implementation as I was only really using the method name. This workaround, obviously, is only possible if one has access to the code.

**Comment by graemerocher** [comment]
ok thanks for the report, we will take a look
