### ISSUE TITLE
micronaut-inject-java and lombok library is  having conflicts

### ISSUE THREAD

**Issue by vikas-shrivastav** [micronaut-projects/micronaut-core#10317]
### Expected Behavior

I have a  HttpServerFilter class which uses RequiredArgsConstructor lombok 
I got a rest controller mentioned in the following repo.
Repo Details:
https://github.com/vikas-shrivastav-mns/MN4Latest

When I hit my rest endpoint:http://localhost:8080/hello

I am getting following error
`Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).`

to fix this I tried adding dependency of  ` io.micronaut:micronaut-inject-java`

after add this  I am getting following error:
`Caused by: java.lang.NoSuchMethodError: com.example.AuthFilter: method 'void <init>()' not found`

### Version

4.2.1

**Comment by dstepanov** [comment]
Lombok needs to be first in the order of the annotation processors

**Comment by vikas-shrivastav** [comment]
When I add lombok at first in the order of the annotation processor, Then I am getting an error again  for micronaut-inject-java

`Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).`

**Comment by dstepanov** [comment]
We have these reports all the time. People use Lombok without understanding what it generates. If you use Intellij you can delombok it and see what is missing. I suspect the annotations are not copied to the constructor.

**Comment by gabriellersa** [comment]
How did you resolve this? @vikas-shrivastav-mns

**Comment by Discordia** [comment]
If I generate a project with this:
```
mn create-app example.micronaut.micronautguide \                                                                                                                                                                                                                                                                                                                                                                                                                                          [15:22:41]
    --features=validation,lombok \
    --build=gradle \
    --lang=java \
    --test=junit
```

And then do a simple constructor injection where the constructor is created by `@AllArgsConstructor` or `@RequiredArgsCosntructor`. I get the error:
```
Caused by: java.lang.NoSuchMethodError: com.example.AuthFilter: method 'void <init>()' not found
```

I tested this after upgrading a project from MN 4.2.2 to 4.8.0 and was getting this problem.

**Comment by dstepanov** [comment]
See https://github.com/micronaut-projects/micronaut-core/issues/11716#event-17174161226
