### ISSUE TITLE
Introspected.Property issue: the field is not accessible for visibility

### ISSUE THREAD

**Issue by msupic** [micronaut-projects/micronaut-core#12742]
### Actual Behaviour

The compileJava gradle task fails when a property from an openapi generated classes starts with '$' like in this example:
```
    @Nullable
    @JsonProperty(JSON_PROPERTY_$_REF)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String $ref;
```

### Steps To Reproduce

The `micronaut-kubernetes-client-openapi-common` module uses the openapi gradle plugin to create a kubernetes client from the spec. One of created classes contains:
```
    @Nullable
    @JsonProperty(JSON_PROPERTY_$_REF)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String $ref;
```
After I upgraded micronaut version from 5.0.3 to 5.1.2 in micronaut-kubernetes, I started getting this error in builds:
```
micronaut-kubernetes/kubernetes-client-openapi-common/build/generated/openapi/generateClientOpenApiModels/src/main/java/io/micronaut/kubernetes/client/openapi/model/V1JSONSchemaProps.java:134: error: Element annotated with @Introspected.Property cannot be used as an introspected property: the field is not accessible for visibility [DEFAULT]
    private String $ref;
```

### Version

5.1.2
