### ISSUE TITLE
3.6.x regression `Provider io.micronaut.annotation.processing.TypeElementVisitorProcessor could not be instantiated`

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#7652]
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.micronaut.annotation.processing.TypeElementVisitorProcessor could not be instantiated: java.lang.ExceptionInInitializerError
```

To reproduce, checkout the `test-resources-integration` branch of the Maven plugin, then `mvn install` it, then try to compile the following application:

[demo.zip](https://github.com/micronaut-projects/micronaut-core/files/9065661/demo.zip)

Possibly caused by #7608 or #7651 

Blocks https://github.com/micronaut-projects/micronaut-maven-plugin/pull/398

**Comment by sdelamo** [comment]
@alvarosanchez @yawkat is this solved?

**Comment by alvarosanchez** [comment]
Yes. Don't know why the PR didn't close this issue . Closing
