### ISSUE TITLE
Simple websocket app fails to compile in 2.4.0

### ISSUE THREAD

**Issue by burtbeckwith** [micronaut-projects/micronaut-core#5114]
See the example app at https://github.com/burtbeckwith/websocket_240

If you clone it and run `./gradlew compileJava` it fails with

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
        ...
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/micronaut/http/uri/UriMatchTemplate
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
        ...
Caused by: java.lang.NoClassDefFoundError: io/micronaut/http/uri/UriMatchTemplate
        at io.micronaut.validation.websocket.WebSocketVisitor.visitMethod(WebSocketVisitor.java:73)
        ...
Caused by: java.lang.ClassNotFoundException: io.micronaut.http.uri.UriMatchTemplate
        ... 187 more
```

If you downgrade the app to 2.3.4 by changing the version in gradle.properties and dropping the application plugin version to 1.3.4 it compiles and runs successfully.

**Comment by graemerocher** [comment]
The fix here is that `inject-java` looks like it needs to depend on the `http` module or the `http` module has to be added to the annotation processor classpath

**Comment by jameskleeh** [comment]
This is because `http` was changed to be a `compileOnly` dependency of `validation`. It seems we should revert that change for 2.4.1

**Comment by graemerocher** [comment]
No that would be incorrect thing to do. Validation has nothing to do with `http` and has no direct dependency on it other than these compile time checkers.

**Comment by jameskleeh** [comment]
I realize that but `inject-java` also doesn't have anything to do with `http`. The correct fix is to move the validators to a separate module, however first we need to revert the breaking change.

**Comment by graemerocher** [comment]
Reverting the breaking change can be achieved without altering the dependency graph.

The `parent` pom can be modified to include these dependency in the annotation processor classpath by default for maven and the Gradle plugin can be modified to the same. Quickly applying a revert that is the wrong thing to do is not the way forward IMO

**Comment by jameskleeh** [comment]
What problems will be caused by re-adding it as an api dependency of validation?

**Comment by graemerocher** [comment]
It will be brought in transitively into applications at runtime for projects that depend on validation but don't require anything to do with http

**Comment by jameskleeh** [comment]
I don't see that as a major concern compared to writing custom logic in build plugins (thus requiring them to be used)

**Comment by graemerocher** [comment]
I personally do so will work on a PR that can be discussed with the team since it is not only about what a single person thinks 😉

**Comment by jameskleeh** [comment]
Sounds good
