### ISSUE TITLE
NoClassDefFoundError: io/micronaut/core/annotation/Introspected$IntrospectionBuilder

### ISSUE THREAD

**Issue by choufraise** [micronaut-projects/micronaut-core#9841]
### Expected Behavior

When bumping `micronaut-parent` from 4.0.6 to 4.1.0 I expect compilation to still succeed.

### Actual Behaviour

Compilation fail due to:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project <my-project>: Fatal error compiling: java.lang.NoClassDefFoundError: io/micronaut/core/annotation/Introspected$IntrospectionBuilder: io.micronaut.core.annotation.Introspected$IntrospectionBuilder
``` 
The _only_ change is the `micronaut-parent` bump from 4.0.6 to 4.1.0. Very weird imo. 

### Steps To Reproduce
POM:
```
    <parent>
        <groupId>io.micronaut.platform</groupId>
        <artifactId>micronaut-parent</artifactId>
        <version>4.1.0</version>
    </parent>
...
    <dependencies>
...
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-core</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-jackson-databind</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.validation</groupId>
            <artifactId>micronaut-validation</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.beanvalidation</groupId>
            <artifactId>micronaut-hibernate-validator</artifactId>
            <version>${micronaut.hibernate.validator.version}</version>
            <scope>compile</scope>
        </dependency>
...
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.micronaut.maven</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${jdk.version}</source>
                    <target>${release.version}</target>
                    <annotationProcessorPaths combine.children="append">
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-inject-java</artifactId>
                            <version>${micronaut.core.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut.validation</groupId>
                            <artifactId>micronaut-validation-processor</artifactId>
                            <version>${micronaut.validation.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amicronaut.processing.group=com.example</arg>
                        <arg>-Amicronaut.processing.module=my-project</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
...
        </plugins>
    </build>
```

### Environment Information

- OS: Ubuntu
- JDK: 17
``` 
$ java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-120.04.2)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-120.04.2, mixed mode, sharing)
``` 

### Version

4.1.0

**Comment by graemerocher** [comment]
looks like the annotation processor path used by maven is incorrect somehow

**Comment by choufraise** [comment]
@graemerocher could you please be a bit more specific? to me it _really feels_ like a clash between core versions as `Introspected$IntrospectionBuilder` is new in core `4.1.0`. 

Actually, the `micronaut-parent:4.1.0` includes property `<micronaut-maven-plugin.version>4.0.6</micronaut-maven-plugin.version>` which in turn depends on `micronaut-core` version `4.0.6` (which _do not_ contain the `IntrospectionBuilder` class.

**Comment by choufraise** [comment]
The `micronaut-maven-plugin` POM states the following:

```
    <parent>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-plugin-parent</artifactId>
        <version>4.0.6</version>
    </parent>

    <artifactId>micronaut-maven-plugin</artifactId>
    <packaging>maven-plugin</packaging>
    <name>Micronaut Maven Plugin - Plugin</name>
    <description>Maven plugin to execute and package Micronaut applications</description>

    <dependencies>
        <!-- Internal dependencies -->
        <dependency>
            <groupId>io.micronaut.maven</groupId>
            <artifactId>micronaut-maven-core</artifactId>
            <version>${project.version}</version>
        </dependency>
...
``` 
This means that it will always use `micronaut-core` with the same version as the plugin. Hence the plugin _must_ follow the `micronaut.core.version` property set in `micronaut-platform` to function correctly. I call bug. :see_no_evil:

**Comment by mryan43** [comment]
Running into the same issue (using maven and 4.1.0), is there a workaround to fix the compiler classpath or should I revert to 4.0.6 ?

**Comment by turneand** [comment]
Hit the same issue myself earlier, definitely new in 4.1.0, but I've managed to isolate it to the micronaut-validation-processor

### Simpler Example:
Create a record to ensure the annotation processors do their thing:
```
package simple;
@io.micronaut.serde.annotation.Serdeable
record SimpleRecord(String id) {}
```

Then maven pom containing only the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>io.micronaut.platform</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>4.1.0</version>
  </parent>

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.1</version>
  <packaging>jar</packaging>

  <properties>
    <jdk.version>17</jdk.version>
    <release.version>17</release.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.micronaut.serde</groupId>
      <artifactId>micronaut-serde-jackson</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>

        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-inject-java</artifactId>
              <version>${micronaut.version}</version>
            </path>
            <path>
              <groupId>io.micronaut.validation</groupId>
              <artifactId>micronaut-validation-processor</artifactId>
              <version>${micronaut.validation.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

### Issue
Issue appears to be in the -processorpath the maven compiler is using (not the project dependencies, they're all correct).
You can see it's picking up micronaut-core 4.0.3

```
mvn compile -X
...
-processorpath $m2repo/io/micronaut/micronaut-inject-java/4.1.0/micronaut-inject-java-4.1.0.jar:$m2repo/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:$m2repo/io/micronaut/micronaut-core-processor/4.1.0/micronaut-core-processor-4.1.0.jar:$m2repo/io/micronaut/micronaut-aop/4.1.0/micronaut-aop-4.1.0.jar:$m2repo/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:$m2repo/org/ow2/asm/asm/9.5/asm-9.5.jar:$m2repo/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:$m2repo/com/github/javaparser/javaparser-symbol-solver-core/3.25.4/javaparser-symbol-solver-core-3.25.4.jar:$m2repo/com/github/javaparser/javaparser-core/3.25.4/javaparser-core-3.25.4.jar:$m2repo/io/micronaut/micronaut-core-reactive/4.1.0/micronaut-core-reactive-4.1.0.jar:$m2repo/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar:$m2repo/io/micronaut/validation/micronaut-validation-processor/4.0.2/micronaut-validation-processor-4.0.2.jar:$m2repo/io/micronaut/micronaut-inject/4.0.3/micronaut-inject-4.0.3.jar:$m2repo/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar:$m2repo/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:$m2repo/io/micronaut/micronaut-core/4.0.3/micronaut-core-4.0.3.jar:$m2repo/io/micronaut/validation/micronaut-validation/4.0.2/micronaut-validation-4.0.2.jar:$m2repo/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar:$m2repo/io/micronaut/reactor/micronaut-reactor/3.0.2/micronaut-reactor-3.0.2.jar:$m2repo/io/projectreactor/reactor-core/3.5.7/reactor-core-3.5.7.jar:
...
```

### Workaround
Add the following to the start of the annotation processors:
```
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-core-processor</artifactId>
              <version>${micronaut.version}</version>
            </path>
```

**Comment by alvarosanchez** [comment]
Let me shed some light about this issue. The problem is that the original POM is incorrect, it's not inheriting the configuration from the parent and it needs exclusions in the annotation processor paths:

```xml
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>io.micronaut.serde</groupId>
              <artifactId>micronaut-serde-processor</artifactId>
              <version>${micronaut.serialization.version}</version>
              <exclusions>
                <exclusion>
                  <groupId>io.micronaut</groupId>
                  <artifactId>micronaut-inject</artifactId>
                </exclusion>
              </exclusions>
            </path>
            <path>
              <groupId>io.micronaut.validation</groupId>
              <artifactId>micronaut-validation-processor</artifactId>
              <version>${micronaut.validation.version}</version>
              <exclusions>
                <exclusion>
                  <groupId>io.micronaut</groupId>
                  <artifactId>micronaut-inject</artifactId>
                </exclusion>
              </exclusions>
            </path>
          </annotationProcessorPaths>
```

Also `micronaut-inject-java` shouldn't be added. If in doubt, always check [what Micronaut Launch generates](https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=MAVEN&test=JUNIT&features=validation&version=4.1.0&activity=preview&showing=/pom.xml) for a new project. 

The root cause of this issue is https://issues.apache.org/jira/browse/MCOMPILER-391, and has nothing to do with the Micronaut Maven Plugin's own dependencies.

Once they release a new version of the compiler plugin, we will adapt what Micronaut Launch generates to simplify this configuration.

**Comment by Kidlike** [comment]
> Also micronaut-inject-java shouldn't be added

@alvarosanchez Do you mean because of `combine.children="append"`, or because it's generally not needed at all anymore?

I'm trying to upgrade from Micronaut 4.0.5 to 4.1.10, and while the `exclusions` fix the issue on command-line (maven build + jUnits), this error is still thrown by IntelliJ no matter what I do...

**Comment by alvarosanchez** [comment]
> @alvarosanchez Do you mean because of `combine.children="append"`, or because it's generally not needed at all anymore?

Generally not needed.

**Comment by stefanos-kalantzis** [comment]
Thank you @turneand, [the workaround](https://github.com/micronaut-projects/micronaut-core/issues/9841#issuecomment-1716149082) works!!!

@alvarosanchez I don't think this is true... I was getting a lot of different errors without the `micronaut-inject-java` annotation-processor. Maybe you are on Java 21, which loads all annotation processors found on the classpath by default? FYI [this is removed again in Java 22](https://bugs.openjdk.org/browse/JDK-8306819).

**Comment by alvarosanchez** [comment]
micronaut-inject-java is not needed explicitly, see what Micronaut Launch generates: https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=MAVEN&test=JUNIT&features=validation&version=4.1.0&activity=preview&showing=/pom.xml

**Comment by stefanos-kalantzis** [comment]
This is just because of `combine.children="append"`. It comes from the parent pom :)
