### PR TITLE
Python: compile imports across source roots and merge the package files of every root

### PR DESCRIPTION
**Pull request by graemerocher**
> Stacked on #13228 (part 24/32 of the Python fix stack; merge in order — GitHub retargets each PR when its base merges).

Fixes two gaps of the Python compiler (`micronaut-inject-python`) that show up as soon as the main and the test Python sources of a project are compiled separately, each by its own `PythonCompile` task into its own output directory, as the Gradle plugin does. Every module documentation port so far had to work around them by merging `src/main/python` and `src/test/python` into one directory compiled with the tests.

### Root cause

1. **Imports across source roots resolved to `Object`.** The processor (`micronaut_processor.py`) resolved `from example.greeting_service import GreetingService` only against the files of the source root being compiled. A module living in another root (the main sources, or a library jar) was not found, so the import fell through to a Java-style lookup of `example.greeting_service.GreetingService`, which does not exist: the type of every injection point, parameter or field annotated with the imported class degraded to `Object`.
2. **The generated package files of two roots shadowed each other at run time.** Each compilation wrote a `GRAALPY-VFS/micronaut-application/src/<package>/__init__.py` (and `__main__.py` for the root) listing the members it knew: the classes of its own modules, the decorators and `java.type` bindings of the Java classes its sources import. GraalPy merges the virtual file system roots on the class path into one namespace, but a file present in several roots is served from one of them, so `from jakarta.inject import Named` in a test failed with `ImportError: cannot import name ...` whenever the main root's `jakarta/inject/__init__.py` (which only listed `Singleton`) won, and `from example import GreetingService` from the package saw only the winning root's classes. Importing a compiled Python class from its package (`from example import GreetingService`) was worse still: the transformer took the bridge class found on the class path for a Java type and generated a `java.type(...)` shim package for `example`, colliding with the user package initialiser ("Output stream or writer has already been opened").

### Fix

* `PythonJavaTypes.isPythonClass` recognises the generated bridge of a Python class (annotated with `@PythonClass`) on the class path. The processor resolves an import whose module is not in the root being compiled to the bridge named after the module's package and the class (`example.GreetingService`, `python.Foo` for a top-level module — the `python.` fallback applies to a top-level module only, not to a package), for absolute and relative imports, so types imported from another root or jar are compiled with their Java type and injection works across roots. The transformer keeps such an import as a Python import instead of rewriting it to the Java bridge (and no longer generates a shim package for it), in both the compile-time and the runtime transformation.
* Package initialisers are now root-agnostic: every compilation writes the members it contributes to a package to a module named `__micronaut_members_<content hash>.py` next to the initialiser, and the generated `__init__.py`, identical in every root, merges the members of all such modules it finds through `pkgutil`. While the package initialises it resolves members on demand (module `__getattr__`), so a module importing a sibling from the package (`from example import GreetingService`) works regardless of the order in which the roots contribute — and, since every members module binds a member-to-module map before its imports, regardless of the order in which the modules of one contribution are imported: a member of a contribution still being imported is served from that contribution or from the module the map names (review fix, previously a stack-integration commit on #13230). The launcher `__main__.py` merges the top-level modules of every root the same way. Identical contributions of several roots hash to the same file; different ones coexist, whichever root the class path serves first.

No Gradle configuration is needed any more to compile main and test Python sources separately.

### Reproducer

`PythonSourceRootsTest` (inject-python-test) compiles a main root and a test root separately (the main output on the test compile class path) and starts an application context with both outputs: the test root imports a class of the main root from its module and from its package, injects it, and imports names of the `jakarta.inject` shim package the main root does not import, with either root first on the class path. Both tests fail on `5.2.x` (`Output stream or writer has already been opened` and the `Object`-typed injection point). A parameterized test covers a module importing a sibling from its own package in a single root, for both module orderings (`ImportError: cannot import name ... from partially initialized module` before the review fix). The members-module assertions of the compiler specs read the exact number of members modules a compilation writes, so a stale `__micronaut_members_<hash>.py` would fail them. `test-suite-python` gains `src/main/python` (`micronaut.docs.sourceroots.greeting_service`) compiled by `compilePython` and tests in `src/test/python` importing and injecting it, which exercises the Gradle flow end to end; the language guide documents the behaviour ("Main and Test Sources").

### Notes

* The module documentation PRs (r2dbc, serialization, gcp, data, azure, control-panel, grpc, kubernetes, langchain4j, object-storage, openapi, oracle-cloud, pulsar, sourcegen, toml) can drop their `mergePythonSources` / `compilePython.enabled = false` workarounds once this is released.
* The shared Gradle plugin (`io.micronaut.build.python.MicronautPythonPlugin`) must put the main source set's Python compile output on the test Python compile class path: today it adds only `main.getJava().getClassesDirectory()`; it should add `main.getOutput().getClassesDirs()` (which carries `build/classes/python/main` and the dependency on `compilePython`). Core's `test-suite-python` already adds `sourceSets.main.output` itself.
* Extending a Python class of another root at compile time (the bridge is a Java class to the compiler) is not covered by this change.

### CODE REVIEW

File: inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java [hunk 1]
```diff
@@ -113,6 +128,85 @@ def __mro_entries__(self, bases):
...
+                    globals()[name] = value
+                    if name not in members:
+                        members.append(name)
+
+            def resolve(name):
+                # a module of this package importing a member from the package while the package
+                # initialises: merge the remaining modules until one defines the member
+                if not name.startswith('__'):
+                    for contribution_name in contributions:
+                        if contribution_name not in merged:
```
Comment (dstepanov) [inline inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java]: **Blocking regression:** package `example` with `a_service.py` (`@Singleton class GreetingService`) and `b_consumer.py` (`from example import GreetingService`, injecting it) in one root: both land in the same `__micronaut_members_<hash>.py`, `merge()` marks it merged before importing it, and its `__all__` is only set on the file's last line — so when `b_consumer` imports from the package, `resolve()` finds neither the name nor an unmerged contribution:

`ImportError: cannot import name 'GreetingService' from partially initialized module 'example'`

for both module orderings; on #13228 both print "Hello Python". (I see a follow-up commit "package merger serves members of a contribution still being imported" on #13230's branch — it should land here.) Suggest looking the name up on contributions still importing (`sys.modules[__name__ + '.' + c]`), or emitting `__all__`/a name→module map at the top of each members module.

**Review by dstepanov — CHANGES_REQUESTED** [review]
The merged package initializer breaks importing a sibling from its own package in a single source root — reproduced locally against #13228. Details inline. Nits: (1) `_resolve_compiled_python_class` also tries the `python.<Name>` fallback for `from example import X` (no dot in the module), which could pick an unrelated top-level `X` from another root or jar — only use it for top-level module imports. (2) The changed assertions in `CompilerSilentFailureSpec`/`PyronautCompilerSpec`/`PyronautCompilerIncrementalTest` concatenate every members file, which would hide a stale `__micronaut_members_<oldhash>.py`; assert that exactly one remains after an incremental change.

File: inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java (hunk 1 above)
Comment (dstepanov) [reply inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java]: Update: the "package merger serves members of a contribution still being imported" commit in #13230 fixes this (checked locally, the sibling import works there). If #13229 is merged separately, that commit should move here; otherwise this is resolved once both land.

Comment (graemerocher) [reply inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java]: Fixed here in fc111e00c9 (moved down from #13230 and extended): the `resolve()` change of the stack-integration commit is applied on this branch, and every members module now binds `__micronaut_member_modules__ = {"GreetingService": "a_service", ...}` before its imports, so while a contribution is still being imported the initializer serves a member either from the contribution (already bound) or from the module the map names — whichever module the contribution imports first. `PythonSourceRootsTest.aModuleImportsASiblingFromItsOwnPackageInASingleRoot` covers `a_service`/`b_consumer` and `z_service`/`a_consumer` in one root (both fail with the `partially initialized module` ImportError before the fix).

Comment (graemerocher) [reply inject-python/src/main/java/io/micronaut/python/processing/PythonAnnotationProcessor.java]: Moved here in fc111e00c9 (with the member map so both module orderings of one contribution work); the stack-integration commit on #13230 becomes redundant when it is rebased onto this branch.

**Comment by graemerocher** [comment]
Review feedback addressed in fc111e00c9 (added on top, no rebase):

- Package initializer: the `resolve()` fix from #13230 is moved here, and every members module binds a member-to-module map (`__micronaut_member_modules__`) before its imports, so a module importing a sibling from its own package while the package initialises is served whichever module the contribution imports first. `PythonSourceRootsTest` gains a parameterized single-root test for both module orderings (fails with `ImportError: cannot import name ... from partially initialized module` before).
- Nit 1: `_resolve_compiled_python_class` uses the `python.<Name>` fallback only for a top-level module import — not when the dotless module is a package (a directory of the root being compiled or a package of compiled Python classes on the class path).
- Nit 2: the `packageMembers` helpers of `CompilerSilentFailureSpec`, `PyronautCompilerSpec` and `PyronautCompilerIncrementalTest` assert the exact number of members modules (one per contribution; the application modules of a package and the Java shims imported from it are two contributions), so a stale `__micronaut_members_<oldhash>.py` after an incremental change fails the test (the incremental compiler does delete it).
- Description updated accordingly.

Tests: `:micronaut-inject-python:test` (125) and `:micronaut-inject-python-test:test -Ppython-ci` (780) pass; `checkstyleMain` is clean; `:test-suite-python:test -Ppython-ci` is running and will be reported below if anything fails.

**Comment by graemerocher** [comment]
`:test-suite-python:test -Ppython-ci` on fc111e00c9: 210 tests, 207 passed in the full run; the 3 `RouteConditionControllerTest` failures were `ResponseClosedException: Connection closed before response was received` under machine load (no Python or import error in the output) and pass when re-run.

**Review by dstepanov — APPROVED** [review]
Thanks, all addressed. Verified on `fc111e00c9` with `-Ppython-ci`: sibling imports from the package work in a single root in every module ordering (also a three-module chain and a subpackage) and across two source roots in both class-path orders; `PythonSourceRootsTest` (4), `CompilerSilentFailureSpec` (7), `PyronautCompilerSpec` (49), `:micronaut-inject-python:test` (125, incl. the exact-count incremental assertion) and checkstyle pass.

Notes: #13230 now conflicts with this in the `resolve()` block of `PythonAnnotationProcessor` and its stack-integration Java change is redundant (its test updates are still needed). SonarCloud reports one new critical S1192 (`" import "` duplicated 4 times, `PythonAnnotationProcessor.java:486`) — a constant would clear the gate. Minor: `_is_compiled_python_package` calls `visitor_context.getClassElements` directly rather than the cached callback, so each stdlib `from typing import X` scans once.

**Review by dstepanov — APPROVED** [review]
Re-approving `dc515926e4`: rebase onto the updated #13228, commit bodies unchanged (diffed the old and new patches).

**Review by dstepanov — APPROVED** [review]
Re-approving `5be85732cb`: rebase onto the updated parent, all commit bodies unchanged (diffed the old and new patches).

**Review by dstepanov — APPROVED** [review]
Re-approving `5680ae41ba`: rebase onto the updated parent, all commit bodies unchanged (diffed the old and new patches).

**Review by dstepanov — APPROVED** [review]
Re-approving `5beeb757d3`: rebase onto the updated parent, all commit bodies unchanged (diffed the old and new patches).

File: test-suite-python/src/test/java/io/micronaut/context/python/PythonBootstrapStackTest.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+    @Test
+    void theLauncherImportChainStaysShallow() throws Exception {
+        ClassLoader classLoader = getClass().getClassLoader();
+        try (Engine engine = GraalPyEngineFactory.buildPythonEngine()) {
+            Context context = GraalPyContextFactory.buildContext(
+                GraalPyContextFactory.bootstrapHostAccess(classLoader), engine, classLoader);
+            try {
+                Value deepest = context.eval(PythonContextRuntime.PYTHON, RERUN_LAUNCHER_WITH_DEPTH_RECORDER);
+                int depth = deepest.getArrayElement(0).asInt();
+                String module = deepest.getArrayElement(1).asString();
```
Comment (dstepanov) [inline test-suite-python/src/test/java/io/micronaut/context/python/PythonBootstrapStackTest.java:93]: `deepest` starts as `[0, None]` and only gets a name once `find_spec` runs, so if the rerun records no import at all this line reads a null `Value`. I checked what that does rather than assume: against `polyglot-25.3.4.1`, `Value.asValue(null).asString()` throws

```
java.lang.NullPointerException: Cannot convert null value null to Java type 'class java.lang.String' using Value.asString(). You can ensure that the operation is supported using Value.isString().
```

so the test would fail with that NPE instead of reporting the real situation, which is "the recorder never saw an import" — and it fails on the line *before* the assertion, so the depth never even gets checked.

It cannot happen today (the `sys.modules` purge guarantees the VFS modules import again), but it is one path change away: if `/graalpy_vfs/src/` ever stops matching the `__file__` prefix, nothing is purged, nothing re-imports, and a test that silently measures nothing turns into a confusing NPE rather than a clear failure.

Cheapest fix is to assert the measurement happened first:

```java
int depth = deepest.getArrayElement(0).asInt();
assertTrue(depth > 0, "the depth recorder saw no import while re-running the launcher");
```

then read the module name (it is non-null from there on), or default it on the Python side with `deepest[1] or '<none>'`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by dstepanov — APPROVED** [review]
Re-approving `5993de55a8`. This is the one PR in the stack with real behaviour change since my last pass (`5beeb757d3`), so I read all four new commits and ran the suites locally on this head with `-Ppython-ci`: `:micronaut-inject-python:test` (126 tests) and `:test-suite-python:test --tests '*PythonBootstrapStackTest*'` (1 test, 17s) both pass.

`6104a664d3` — the generated package initialiser and launcher now `exec` each members module's code in a namespace of their own instead of importing it through `importlib.import_module` from a nested function. Checked the parts that carry risk:

- **Re-entrancy.** `__micronaut_namespaces[contribution] = namespace` is assigned *before* the `exec`, and `__getattr__`'s merge loop only visits contributions not already in that map, so a members module that imports its own package during its execution cannot re-enter its own merge. That is the guarantee `sys.modules` used to provide for the import path — good that it is preserved explicitly.
- **Partial-member lookup.** The first `__getattr__` loop reads `namespace` directly rather than `vars(partial_module)` and keeps the `__micronaut_member_modules__` fallback through a real `import_module`, so a sibling is still served while a contribution is mid-run.
- **Teardown.** `del __getattr__` in the `finally` preserves the "only during initialisation" window, and `globals().pop('__micronaut_contribution', None)` correctly tolerates the empty-contributions case where the loop variable was never bound.
- **Discovery.** `os.listdir(directory)` over `__path__` replaces `pkgutil.iter_modules`, so discovery is now `.py` files in a real directory. Fine for the VFS layout the compiler writes, and the subpackage check in `__getattr__` moves to `os.path.isdir` consistently — worth keeping in mind if a source root is ever served from anything other than a mounted directory.

`5993de55a8` replacing the fixed thread stack with a Python-frame bound is the right call: the frame count is the property the initialisers actually control, where the stack size per frame is the platform's business, and `cb266f1bb1`'s 512 KB → 576 KB bump is exactly the kind of drift that makes a threshold test untrustworthy. One robustness point inline on the recorder's result handling, not blocking.

`454cdd934d` is literal extraction only.

---
_Generated by [Claude Code](https://claude.ai/code)_
