### ISSUE TITLE
GraalVM's Native Image generation fails since 2.4.1 with Kotlin

### ISSUE THREAD

**Issue by csh0711** [micronaut-projects/micronaut-core#5277]
When using Micronaut 2.4.1 (and 2.4.2 as well) I get an error when creating a Native Image with GraalVM. 
It works with 2.4.0.

Error during generation is:

```
Error: Classes that should be initialized at run time got initialized during image building:
 kotlin.ULong was unintentionally initialized at build time. To see why kotlin.ULong got initialized use --trace-class-initialization=kotlin.ULong

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Working with version 2.4.0:
1. Clone [https://github.com/csh0711/error-micronaut-2-4-1-graalvm-kotlin.git](https://github.com/csh0711/error-micronaut-2-4-1-graalvm-kotlin.git)
2. Switch to branch `master`
3. Switch to GraalVM (e.g. `sdk install java 21.0.0.2.r11-grl` and  `gu install native-image`)
4. Run `./gradlew clean assemble`      
5. Run `native-image --no-server -cp build/libs/hello-world-0.1-all.jar`
6. Build successfull (you can execute `./hello-world`)

**Not** working with version 2.4.1:
1. Switch to branch `mn_2_4_1`
2. Run `./gradlew clean assemble`      
3. Run `native-image --no-server -cp build/libs/hello-world-0.1-all.jar`
5. See error

### Expected Behaviour

Native image should be generated as 2.4.2 is the default version in Micronaut launch

### Actual Behaviour

Doesn't work, see mentioned error above.

### Environment Information

- **Operating System**: Mac OS 10.15.7
- **Micronaut Version:** 2.4.1
- **JDK Version:** GraalVM 21.0.0.2

### Example Application

- GitHub Repo: [https://github.com/csh0711/error-micronaut-2-4-1-graalvm-kotlin.git](https://github.com/csh0711/error-micronaut-2-4-1-graalvm-kotlin.git)

### Further remarks
With Micronaut 2.4.0 the native image generation throws this warning:

`Warning: class initialization of class io.micronaut.validation.exceptions.ValidationExceptionHandler failed with exception java.lang.NoClassDefFoundError: org/grails/datastore/mapping/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.validation.exceptions.ValidationExceptionHandler to explicitly request delayed initialization of this class.`

It's still working but I find it quite confusing, perhaps this might be changed as well?

**Comment by ilopmar** [comment]
Duplicate of #5210. Please update to micronaut-kotlin 2.3.1 that contains the fix. See https://github.com/micronaut-projects/micronaut-kotlin/releases/tag/v2.3.1
