### PR TITLE
fix(ksp): detect @JvmRepeatable when resolving repeatable containers

### PR DESCRIPTION
**Pull request by dstepanov**
## What changed

The repeatable-container lookup in `KotlinVisitorContext.computeRepeatableContainerNameForType` compared the resolved annotation declaration's qualified name against `java.lang.annotation.Repeatable`. For annotations declared in Kotlin source with `@JvmRepeatable`, the KSP model resolves the annotation type to the `kotlin.jvm.JvmRepeatable` typealias declaration, so the comparison never matched and the container was not detected.

The lookup now resolves through `getAnnotationTypeName` (already memoized), which expands the typealias to the binary name before comparing, so `@JvmRepeatable` is recognized the same way as the Java annotation.

## Why

Without container detection, repeated Kotlin annotations were added to the metadata without a repeatable container, so successive occurrences overwrote one another instead of accumulating. All but one value were lost for:

- repeated annotations applied directly to an element,
- repeated annotations used as stereotypes on an annotation class,
- explicitly applied container annotations (which the KSP builder expands into their nested values before processing).

The Java (APT) and Groovy builders already handle the equivalent shapes correctly; this brings KSP in line with them.

## Notes for reviewers

- New `RepeatableStereotypeSpec` in `inject-kotlin` covers the three scenarios above, asserting two retained `PatternLike` values via `getAnnotationValuesByType`, mirroring the existing Java specs.
- The tests assert `hasStereotype` on the container name rather than the repeated annotation name because `hasStereotype(String)` intentionally does not resolve repeatable containers (same behavior on the Java processor).
- While diagnosing this, I found that `AnnotationMetadataHierarchy` never overrides `getStereotypeAnnotationNames()`/`getDeclaredStereotypeAnnotationNames()`, so those always return an empty set on hierarchy metadata regardless of language. That is a separate pre-existing issue and is not addressed here.
- Verified with the new spec, the full `inject-kotlin` suite (793 tests), and `test-suite-kotlin` (one unrelated flaky HTTP test passes in isolation).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by dstepanov** [comment]
### Downstream compatibility check: micronaut-data & micronaut-serialization ✅

I built this PR's merge-into-`5.2.x` commit, published core to an isolated local Maven repository, and built both downstream projects against it.

**Downstream revisions**
- micronaut-data `5.2.x` @ `030461ce2b`
- micronaut-serialization `3.2.x` @ `284da94ac`

**What was run** (baseline for comparison: unmodified `origin/5.2.x`)
- `testClasses` across every module of both projects — this exercises the annotation processors, which is the main exposure for a core change like this one
- micronaut-data tests: `data-processor` (1127), `data-model`, `data-document-processor`, `data-runtime` (360), `data-tx`, `data-connection`
- micronaut-serialization tests: `serde-processor`, `serde-jackson` (1578), `serde-support`, `serde-bson`, `serde-jsonp`, `serde-jsonb`

**Result: no new compilation errors and no new test failures in either project versus the baseline.**

Caveats:
- `DataConversionServiceSpec` has 2 timezone-dependent failures that reproduce identically on the unmodified baseline (CET machine) — unrelated to this PR.
- Container-backed micronaut-data tests (JDBC / R2DBC / Mongo / Hibernate) were not run; no Docker available in the environment.

**Review by graemerocher — APPROVED** [review]
