### ISSUE TITLE
Problem with introspected generic property

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4387]
In `2.1.2` (works ok in `2.1.1`).

I have the following entities:

```kotlin
interface ISettlementTarget
interface IBankAccount: ISettlementTarget

@Entity class BankAccount(): SomeBaseEntity(), IBankAccount

@Entity class BaseSettlement<T: ISettlementTarget>(
    val from: T,
    val to: T
}: SomeBaseEntity()

@Entity
class BankTransfer(
    value: BigDecimal,
    from: IBankAccount,
    to: IBankAccount,
): BaseSettlement<IBankAccount>(from, to)
```

Because `BankTransfer` is an entity class it's introspected, however in `2.1.2` it throws the following exception from the validator:

```
'intr.IBankAccount domain.BankTransfer.getFrom()'
java.lang.NoSuchMethodError: 'intr.IBankAccount domain.BankTransfer.getFrom()'
	at domain.$BankTransfer$Introspection$$13.readInternal(Unknown Source)
	at io.micronaut.core.beans.AbstractBeanProperty.get(AbstractBeanProperty.java:115)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1107)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:153)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:120)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:116)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
	at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:227)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
```

Here is the content of `$BankTransfer$Introspection$$13` for both cases:

```java
// 2.1.2
final class $BankTransfer$Introspection$$13 extends AbstractBeanProperty {

    public Object readInternal(Object var1) {
        return ((BankTransfer)var1).getFrom();
    }

    public void writeInternal(Object var1, Object var2) {
        ((BankTransfer)var1).setFrom((IBankAccount)var2);
    }

    public boolean isReadOnly() {
        return true;
    }
}

// 2.1.1
final class $BankTransfer$Introspection$$13 extends AbstractBeanProperty {

    public Object readInternal(Object var1) {
        return ((BankTransfer)var1).getFrom();
    }

    public void writeInternal(Object var1, Object var2) {
        ((BankTransfer)var1).setFrom((ISettlementTarget)var2);
    }

    public boolean isReadOnly() {
        return true;
    }
}
```

Looking at `writeInternal()`, version from `2.1.2` looks better, because indeed in this class the `from` property is of `IBankAccount` type, not of generic base `ISettlementTarget` type. However it doesn't work.

Standing in `AbstractBeanProperty` I can confirm that for the validated bean there's `getFrom()` gettter and the object kept in this getter is of `IBankAccount` type:

![image](https://user-images.githubusercontent.com/1880196/97191154-dfb31e80-17a6-11eb-8062-c2ef153c8b88.png)

**Comment by l0co** [comment]
I can see the same problem in java now, and it's in simple structure so I can give you a full source:

```java
@Introspected
public abstract class BaseNotificationEvent {

}

public abstract class SimpleNotificationEvent<T> extends BaseNotificationEvent {

	@NotNull protected String message;
	@NotNull protected T recipient;
	@NotNull protected CountryCode country;

	protected boolean raw;

	public SimpleNotificationEvent(@Nonnull String message, @Nonnull T recipient, @Nonnull CountryCode country) {
		this.raw = true;
		this.message = message;
		this.recipient = recipient;
		this.country = country;
	}

	public SimpleNotificationEvent(@Nonnull String messageKey, @Nullable Object model, @Nonnull T recipient,
								   @Nonnull CountryCode country) {
		this.raw = false;
		this.message = messageKey;
		this.recipient = recipient;
		this.country = country;

		this.serializedData = ObjectConverter.instance().convert(model, String.class);
	}

	@Nonnull public String getMessage() {
		return message;
	}

	public void setMessage(@Nonnull String message) {
		this.message = message;
	}

	@Nonnull public T getRecipient() {
		return recipient;
	}

	public void setPhone(@Nonnull T phone) {
		this.recipient = phone;
	}

	@Nonnull
	@Override
	public CountryCode getCountry() {
		return country;
	}

	public void setCountry(@Nonnull CountryCode country) {
		this.country = country;
	}

	public boolean isRaw() {
		return raw;
	}

	public void setRaw(boolean raw) {
		this.raw = raw;
	}
}

public class SmsNotificationEvent extends SimpleNotificationEvent<String> {

	public SmsNotificationEvent(@Nonnull String message, @Nonnull String recipient, @Nonnull CountryCode country) {
		super(message, recipient, country);
	}

	public SmsNotificationEvent(@Nonnull String messageKey, @Nullable Object model, @Nonnull String recipient, @Nonnull CountryCode country) {
		super(messageKey, model, recipient, country);
	}

}

public enum CountryCode {

	AD("AD")

}
```

And the bug log:

```
'java.lang.String io.luna.client.notifier.sms.SmsNotificationEvent.getRecipient()'
java.lang.NoSuchMethodError: 'java.lang.String io.luna.client.notifier.sms.SmsNotificationEvent.getRecipient()'
	at io.luna.client.notifier.sms.$SmsNotificationEvent$Introspection$$1.readInternal(Unknown Source)
	at io.micronaut.core.beans.AbstractBeanProperty.get(AbstractBeanProperty.java:115)
	at io.micronaut.validation.validator.DefaultValidator.doValidate(DefaultValidator.java:1107)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:153)
	at io.micronaut.validation.validator.DefaultValidator.validate(DefaultValidator.java:120)
	at io.luna.client.notifier.Notifier.validate(Notifier.java:310)
	at io.luna.client.notifier.Notifier.send(Notifier.java:322)
	at io.luna.client.notifier.Notifier$BaseNotificationEventBuilder.send(Notifier.java:83)
	at io.luna.service.notifier.test.TwilioTest.testSmsEventFlow(TwilioTest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:117)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by l0co** [comment]
`2.1.3` released without this fixed :)

**Comment by l0co** [comment]
Seems to be fixed in 2.1.4
