### ISSUE TITLE
Build failed with an exception 

### ISSUE THREAD

**Issue by xmlking** [micronaut-projects/micronaut-core#170]
Build failed with exception 
 
```
$ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone https://github.com/micronaut-projects/micronaut-core.git
2. cd micronaut-core
3. ./gradlew publishToMavenLocal

### Expected Behaviour

Build should succeed 

### Actual Behaviour

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Developer/Work/boot/3rdparty/micronaut-core/inject-java/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':inject-java'.
> java.lang.NullPointerException (no error message)

```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** master
- **JDK Version:** 10

```
$ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by rpmcdougall** [comment]
I also ran into this personally on the same revision of Java 10 as well as 9.0.4-openjdk, but it did work on 8.0.171-oracle.

**Comment by menilub** [comment]
> Task :http-client:compileJava FAILED
Note: Creating bean classes for 12 type elements
/Users/menilub/micronaut/micronaut-core/http-client/src/main/java/io/micronaut/http/client/HttpClient.java:131: error: unreported exception X; must be caught or declared to be thrown
                    .orElseThrow(() -> new HttpClientResponseException(
                                ^
  where X,T are type-variables:
    X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
    T extends Object declared in class Optional
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':http-client:compileJava'.
> Compilation failed; see the compiler error output for details.

Environment Information:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by graemerocher** [comment]
Currently to build Micronaut from source you need the latest version of JDK 8 (earlier versions have type inference bugs).

To run Micronaut applications you can use any JDK 8 or above. Please see instructions regarding JDK 9+ support here: https://micronaut-projects.github.io/micronaut-core/snapshot/guide/index.html#java

Thanks for trying Micronaut!

**Comment by JJAM2014** [comment]
I am facing this trouble when launching....../gradlew publishToMavenLocal

D:\micronaut-core-1.0.0.M1\http-client\src\main\java\io\micronaut\http\client\HttpClient.java:131: error: unreported exception X; must be caught or declared to be thrown
                    .orElseThrow(() -> new HttpClientResponseException(
                                ^
  where X,T are type-variables:
    X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
    T extends Object declared in class Optional
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED
version Java
 $ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
